<?php
/*
*
* Return postback
*
*/

require_once('../../../../wp-load.php');
require_once "../wooninja/DinersGW.php";


//Iz uniqid dobimo order
// The gateway sends the uniqid as "id" (see DinersGW::transaction_debit).
// "uniqid" is accepted as a fallback for links generated by older versions.
$uniqid_value = '';
if ( isset( $_GET["id"] ) ) {
	$uniqid_value = sanitize_text_field( $_GET["id"] );
} elseif ( isset( $_GET["uniqid"] ) ) {
	$uniqid_value = sanitize_text_field( $_GET["uniqid"] );
}

$order = false;
if ( $uniqid_value !== '' ) {
	$orders = wc_get_orders( array(
	    'limit'      => 1,
	    'meta_key'   => 'uniqid_bankart',
	    'meta_value' => $uniqid_value,
	) );
	$order = ! empty( $orders ) ? $orders[0] : false;
}
$settings = new BankartDiners();

$shop_url = get_permalink( woocommerce_get_page_id( 'shop' ) );


//Check if order confirmed
// $order can be false when the lookup misses (bad or missing id, or the
// postback has not created the meta yet) - never call methods on it.
if($order && "wc-" . $order->get_status() == $settings->status_success){
	//Potrjen
	
	$url = $order->get_checkout_order_received_url();
	
	?>
	<head>
	  <meta http-equiv="refresh" content="5; url=<?=$url?>">
	</head> 
	
	<div style="width: 300px; margin: auto; height: 100px; margin-top: 50px; text-align: center">
		<h1><?= __('Plačilo je uspešno.', 'woothemes') ?></h1>
		<br />
		<img src="../img/dines-club-checkout.png" />
		<br /><br />
		<a href="<?= $shop_url ?>" style="text-decoration: none; color: black; font-weight: bold"><?= __('Nazaj v trgovino', 'woothemes') ?></a>
	</div>
	<?php
}elseif($order && "wc-" . $order->get_status() == $settings->status_failed){
	//Failano
	?>
	<div style="width: 300px; margin: auto; height: 100px; margin-top: 50px; text-align: center">
		<h1><?= __('Plačilo NI bilo uspešno.', 'woothemes') ?></h1>
		<br />
		<img src="../img/dines-club-checkout.png" />
		<br /><br />
		<a href="<?= $shop_url ?>" style="text-decoration: none; color: black; font-weight: bold"><?= __('Nazaj v trgovino', 'woothemes') ?></a>
	</div>
	<?php
}else{
	//Čakamo
	?>
	<head>
	  <meta http-equiv="refresh" content="5">
	</head> 
	<div style="width: 300px; margin: auto; height: 100px; margin-top: 50px; text-align: center">
		<h1><?= __('Čakamo potrditev plačila', 'woothemes') ?></h1>
		<br />
		<img src="../img/dines-club-checkout.png" />
		<br /><br />
		<a href="<?= $shop_url ?>" style="text-decoration: none; color: black; font-weight: bold"><?= __('Nazaj v trgovino', 'woothemes') ?></a>
	</div>
	<?php
}